- name: cpu-frequency | Copy omen-mode.service to /etc/systemd/system/
  become: true
  ansible.builtin.copy:
    src: cpu-frequency/omen-mode.service
    dest: /etc/systemd/system/omen-mode.service
    owner: root
    group: root
    mode: "0644"

- name: cpu-frequency | Apply persistent cpu-frequency
  become: true
  ansible.builtin.systemd_service:
    name: omen-mode.service
    state: started
    enabled: true
