- name: intel-undervolt | Configuration
  become: true
  ansible.builtin.copy:
    src: intel-undervolt/intel-undervolt.conf
    dest: /etc/intel-undervolt.conf
    owner: root
    group: root
    mode: "0644"

- name: intel-undervolt | Apply persistent undervolt
  become: true
  ansible.builtin.systemd_service:
    name: intel-undervolt.service
    state: started
    enabled: true
