- name: thunderbolt | Automatically connect any device
  become: true
  ansible.builtin.lineinfile:
    create: true
    path: "/etc/udev/rules.d/99-removable.rules"
    line: 'ACTION=="add", SUBSYSTEM=="thunderbolt", ATTR{authorized}=="0", ATTR{authorized}="1"'
    mode: "0660"
    state: present
