- name: thunderbolt | Automatically connect any device
  become: true
  ansible.builtin.copy:
    src: thunderbolt/99-removable.rules
    dest: /etc/udev/rules.d/99-removable.rules
    owner: root
    group: root
    mode: "0660"
